Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from tespy.tools.helpers import get_chem_ex_lib

chemexlib = get_chem_ex_lib("Ahrendts")

ean_gt = ExergyAnalysis(nwk, E_F=[fuel_input, air_input], E_P=[power_output], E_L=[chimney])
ean_gt.analyse(p0, T0, Chem_Ex=chemexlib)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[12], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtespy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtools[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhelpers[39;00m [38;5;28;01mimport[39;00m get_chem_ex_lib
[1;32m      3[0m chemexlib [38;5;241m=[39m get_chem_ex_lib([38;5;124m"[39m[38;5;124mAhrendts[39m[38;5;124m"[39m)
[1;32m      5[0m ean_gt [38;5;241m=[39m ExergyAnalysis(nwk, E_F[38;5;241m=[39m[fuel_input, air_input], E_P[38;5;241m=[39m[power_output], E_L[38;5;241m=[39m[chimney])

[0;31mImportError[0m: cannot import name 'get_chem_ex_lib' from 'tespy.tools.helpers' (/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/tespy/tools/helpers.py)

