Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import plotly.graph_objects as go

links, nodes = ean.generate_plotly_sankey_input()

fig = go.Figure(go.Sankey(
    arrangement="snap",
    node={"label": nodes, 'pad': 11, 'color': 'orange'},
    link=links
    ))
# plot(fig, filename='chp_grassmann')
fig.show()

links_el, nodes_el = ean_el.generate_plotly_sankey_input()

fig_el = go.Figure(
    go.Sankey(
        arrangement="snap",
        node={"label": nodes_el, 'pad': 11, 'color': 'orange'},
        link=links_el
        ),
    layout=go.Layout({'width': 800})
    )

fig_el.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[9], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgraph_objects[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgo[39;00m
[1;32m      3[0m links, nodes [38;5;241m=[39m ean[38;5;241m.[39mgenerate_plotly_sankey_input()
[1;32m      5[0m fig [38;5;241m=[39m go[38;5;241m.[39mFigure(go[38;5;241m.[39mSankey(
[1;32m      6[0m     arrangement[38;5;241m=[39m[38;5;124m"[39m[38;5;124msnap[39m[38;5;124m"[39m,
[1;32m      7[0m     node[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mlabel[39m[38;5;124m"[39m: nodes, [38;5;124m'[39m[38;5;124mpad[39m[38;5;124m'[39m: [38;5;241m11[39m, [38;5;124m'[39m[38;5;124mcolor[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124morange[39m[38;5;124m'[39m},
[1;32m      8[0m     link[38;5;241m=[39mlinks
[1;32m      9[0m     ))

[0;31mModuleNotFoundError[0m: No module named 'plotly'
ModuleNotFoundError: No module named 'plotly'

